### ISSUE TITLE
Invisible Bins in exported STL

### ISSUE THREAD

**Issue by mightyrival** [node-dojo/dojo-recursive-bins#6]
Hello! I'm checking the "make exportable" box and exporting an individual bin as an .stl file. Then opening the file in Anker Slice — it exists (shows the measurements) but the object itself is invisible. 

This is my first time using Blender — am I missing a step before exporting? I also tried exporting as an OBJ, but Anker Slice says that file is damaged.

**Comment by node-dojo** [comment]
My guess is you're exporting it at 1/1000th the scale the slicer is anticipating. Try exporting the STL from blender with different export settings or try to select the object in the slicer and scale it up. Usually needs to be either 10x, 100x, or 1000x bigger.

This is because different softwares interpret units differently. Like your slicer might consider 1 unit = 1 mm, but your blender export said 0.001 units = 1 mm, or 1 = 1 meter.

**Comment by mightyrival** [comment]
Thanks! I had been zooming out to find it off-centre, but zoomed in and there it was dead centre, a fraction of a mm wide.
